#+TITLE:  =venv=, =pip= et =ipython=
#+AUTHOR: Xavier Garrido
#+DATE:   14/01/2017
#+OPTIONS: toc:nil ^:{}
#+LATEX_HEADER: \setcounter{chapter}{0}

* L'écosystème Python

1) Définir un environnement virtuel que l'on placera dans le répertoire
   =~/option_python=.

2) Charger ce nouvel environnement et s'assurer que la commande =python= pointe
   bien vers le répertoire =bin= du répertoire =~/option_python=.

3) Lister les modules actuellement installés puis suivre les recommendations
   issues de la précédente commande.

4) Installer la version =1.5.2= de la librarie =matplotlib= puis mettez à jour cette
   dernière.

5) Installer l'interpréteur =ipython= et l'utiliser pour afficher la chaîne de
   caractères ="Bonjour tout le monde"=

6) Définir une première variable =x1= égale à 10 et une seconde =x2= égale à
   10.0. Afficher le statut des variables.

7) Afficher la partie réelle puis la partie imaginaire de =x1=. Afficher la taille
   en bits de =x1=. Lors des différentes opérations, on pourra se servir de
   l'auto-complétion et de la commande d'aide =?= pour accéder à la documentation
   de chaque commande.

8) Afficher la documentation de la fonction =input= puis se servir de cette
   fonction pour demander à l'utilisateur la saisie d'un nombre =y=.

#+BEGIN_REMARK
Dans toute la suite de cette option et notamment lors des prochains exercices,
on prendra bien garde de systématiquement charger l'environnement virtuel défini
lors de ce premier exercice.
#+END_REMARK

* La calculatrice Python

1) Dans l'interpréteur =ipython= réaliser les opérations arithmétiques d'addition,
   soustraction, multiplication et division sur des nombres entiers ainsi que
   sur des nombres flottants.

2) Comparer le résultat de la division de deux entiers lorsque vous utilisez
   l'opérateur =/= et =//=. Dans le second cas,

3) À l'aide de la fonction =type= dont on cherchera le fonctionnement à l'aide de
   l'opérateur =?= de =ipython=, afficher la nature de nombres entier et flottant.

4) Déclarer deux nombres =i = 10= et =x = 10.0= et tester leur égalité /via/
   l'opérateur ====. Stocker ce résultat dans une variable =test= et retourner son
   type.
